// Generated by Classiq.
// Classiq version: 0.50.0
// Creation timestamp: 2024-09-26T02:59:45.604936+00:00
// Random seed: 3507303778

OPENQASM 2.0;
include "qelib1.inc";
gate main_identity_0 q0 {
}

gate main_identity_1 q0,q1,q2,q3 {
}

gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate prep_ancilla_0_statepreparation_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate prep_ancilla_0_statepreparation_rygate_1 q0,q1 {
  prep_ancilla_0_statepreparation_rygate_1_mcx_0 q1,q0;
  ry(-0.001961335930211545) q0;
  prep_ancilla_0_statepreparation_rygate_1_mcx_0 q1,q0;
  ry(0.001961335930211545) q0;
}

gate mcx_hybrid_gray_code_maslov15_139644200141776 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_139644074554064_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_139644200141776 q0,q1,q2;
  x q0;
  x q1;
}

gate prep_ancilla_0_statepreparation_rygate_2_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_139644074554064_o0 q0,q1,q2;
}

gate prep_ancilla_0_statepreparation_rygate_2 q0,q1,q2 {
  prep_ancilla_0_statepreparation_rygate_2_mcx_0 q1,q2,q0;
  ry(-0.06842744166965213) q0;
  prep_ancilla_0_statepreparation_rygate_2_mcx_0 q1,q2,q0;
  ry(0.06842744166965213) q0;
}

gate r1tof q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_139644200150736 q0,q1,q2,q3,q4 {
  r1tof q0,q1,q4;
  ccx q4,q2,q3;
  r1tof q0,q1,q4;
}

gate mcx_hybrid_gray_code_maslov15_o0_139644200153424_o0 q0,q1,q2,q3,q4 {
  x q0;
  x q1;
  x q2;
  mcx_hybrid_gray_code_maslov15_139644200150736 q0,q1,q2,q3,q4;
  x q0;
  x q1;
  x q2;
}

gate prep_ancilla_0_statepreparation_rygate_3_mcx_0 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_o0_139644200153424_o0 q0,q1,q2,q3,q4;
}

gate prep_ancilla_0_statepreparation_rygate_3 q0,q1,q2,q3,q4 {
  prep_ancilla_0_statepreparation_rygate_3_mcx_0 q1,q2,q3,q0,q4;
  ry(-0.30627736916966936) q0;
  prep_ancilla_0_statepreparation_rygate_3_mcx_0 q1,q2,q3,q0,q4;
  ry(0.30627736916966936) q0;
}

gate prep_ancilla_0_statepreparation q0,q1,q2,q3,q4 {
  ry(9.527425386396606e-07) q3;
  prep_ancilla_0_statepreparation_rygate_1 q2,q3;
  prep_ancilla_0_statepreparation_rygate_2 q1,q2,q3;
  prep_ancilla_0_statepreparation_rygate_3 q0,q1,q2,q3,q4;
}

gate main_prep_ancilla_0 q0,q1,q2,q3,q4 {
  prep_ancilla_0_statepreparation q0,q1,q2,q3,q4;
}

gate operate_iteration_0_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
  x q3;
}

gate r1tof4 q0,q1,q2,q3 {
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
}

gate r1tof4_dg q0,q1,q2,q3 {
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_139643836056912 q0,q1,q2,q3,q4,q5 {
  r1tof4 q0,q1,q2,q5;
  ccx q5,q3,q4;
  r1tof4_dg q0,q1,q2,q5;
}

gate operate_iteration_0_igate_mcx_0 q0,q1,q2,q3,q4,q5 {
  mcx_hybrid_gray_code_maslov15_139643836056912 q0,q1,q2,q3,q4,q5;
}

gate ccircuit_1150089 q0,q1 {
}

gate operate_iteration_0_igate q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
  ccircuit_1150089 q6,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
}

gate operate_iteration_0_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
  x q1;
  x q0;
}

gate operate_iteration_0 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_0_igate q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_0_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_1_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
  x q2;
  x q3;
}

gate rcccx q0,q1,q2,q3 {
  u2(0,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
}

gate rcccx_dg q0,q1,q2,q3 {
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(-2*pi,pi) q3;
}

gate mcx q0,q1,q2,q3,q4 {
  h q4;
  cu1(pi/2) q3,q4;
  h q4;
  rcccx q0,q1,q2,q3;
  h q4;
  cu1(-pi/2) q3,q4;
  h q4;
  rcccx_dg q0,q1,q2,q3;
  c3sqrtx q0,q1,q2,q4;
}

gate mcx_hybrid_gray_code_maslov15_139643973933200 q0,q1,q2,q3,q4 {
  mcx q0,q1,q2,q3,q4;
}

gate operate_iteration_1_compose_mcx_0 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_139643973933200 q0,q1,q2,q3,q4;
}

gate ccompose_expanded___12 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_1_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___12 q0,q1;
}

gate operate_iteration_1_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
  operate_iteration_1_compose_compose_aux_control_name q6,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
}

gate operate_iteration_1_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
  x q1;
}

gate operate_iteration_1 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_1_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_1_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_1_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_2_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q2;
  x q3;
}

gate operate_iteration_2_rzgate q0,q1,q2,q3,q4,q5 {
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(2*pi) q0;
}

gate operate_iteration_2_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
  x q0;
}

gate operate_iteration_2 q0,q1,q2,q3,q4,q5 {
  operate_iteration_2_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_2_rzgate q0,q1,q2,q3,q4,q5;
  operate_iteration_2_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_3_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q2;
  x q3;
}

gate ccompose_expanded___25 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_3_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___25 q0,q1;
}

gate operate_iteration_3_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  operate_iteration_3_compose_compose_aux_control_name q5,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
}

gate operate_iteration_3_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
}

gate operate_iteration_3 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_3_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_3_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_3_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_4_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q3;
}

gate operate_iteration_4_igate q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  ccircuit_1150089 q5,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
}

gate operate_iteration_4_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q1;
  x q0;
}

gate operate_iteration_4 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_4_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_4_igate q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_4_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_5_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
  x q3;
}

gate ccompose_expanded___38 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_5_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___38 q0,q1;
}

gate operate_iteration_5_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
  operate_iteration_5_compose_compose_aux_control_name q6,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
}

gate operate_iteration_5_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q1;
}

gate operate_iteration_5 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_5_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_5_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_5_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_6_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q3;
}

gate operate_iteration_6_rzgate q0,q1,q2,q3,q4,q5 {
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(2*pi) q0;
}

gate operate_iteration_6_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q0;
}

gate operate_iteration_6 q0,q1,q2,q3,q4,q5 {
  operate_iteration_6_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_6_rzgate q0,q1,q2,q3,q4,q5;
  operate_iteration_6_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_7_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q3;
}

gate ccompose_expanded___51 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_7_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___51 q0,q1;
}

gate operate_iteration_7_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  operate_iteration_7_compose_compose_aux_control_name q5,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
}

gate operate_iteration_7_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
}

gate operate_iteration_7 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_7_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_7_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_7_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_8_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
}

gate operate_iteration_8_igate q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  ccircuit_1150089 q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_8_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
  x q1;
  x q0;
}

gate operate_iteration_8 q0,q1,q2,q3,q4,q5 {
  operate_iteration_8_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_8_igate q0,q1,q2,q3,q4,q5;
  operate_iteration_8_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_9_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
  x q2;
}

gate ccompose_expanded___64 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_9_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___64 q0,q1;
}

gate operate_iteration_9_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
  operate_iteration_9_compose_compose_aux_control_name q6,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
}

gate operate_iteration_9_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
  x q1;
}

gate operate_iteration_9 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_9_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_9_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_9_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_10_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q2;
}

gate operate_iteration_10_rzgate q0,q1,q2,q3,q4,q5 {
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(2*pi) q0;
}

gate operate_iteration_10_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
  x q0;
}

gate operate_iteration_10 q0,q1,q2,q3,q4,q5 {
  operate_iteration_10_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_10_rzgate q0,q1,q2,q3,q4,q5;
  operate_iteration_10_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_11_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q2;
}

gate ccompose_expanded___77 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_11_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___77 q0,q1;
}

gate operate_iteration_11_compose q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  operate_iteration_11_compose_compose_aux_control_name q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_11_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
}

gate operate_iteration_11 q0,q1,q2,q3,q4,q5 {
  operate_iteration_11_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_11_compose q0,q1,q2,q3,q4,q5;
  operate_iteration_11_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_12_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
}

gate operate_iteration_12_igate q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  ccircuit_1150089 q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_12_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q1;
  x q0;
}

gate operate_iteration_12 q0,q1,q2,q3,q4,q5 {
  operate_iteration_12_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_12_igate q0,q1,q2,q3,q4,q5;
  operate_iteration_12_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_13_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
}

gate ccompose_expanded___90 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_13_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___90 q0,q1;
}

gate operate_iteration_13_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
  operate_iteration_13_compose_compose_aux_control_name q6,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
}

gate operate_iteration_13_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q1;
}

gate operate_iteration_13 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_13_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_13_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_13_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_14_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
}

gate operate_iteration_14_rzgate q0,q1,q2,q3,q4,q5 {
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(2*pi) q0;
}

gate operate_iteration_14_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q0;
}

gate operate_iteration_14 q0,q1,q2,q3,q4,q5 {
  operate_iteration_14_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_14_rzgate q0,q1,q2,q3,q4,q5;
  operate_iteration_14_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate ccompose_expanded___98 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_15_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___98 q0,q1;
}

gate operate_iteration_15_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  operate_iteration_15_compose_compose_aux_control_name q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_15 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_15_compose q0,q1,q2,q3,q4,q5,q6;
}

gate main_operate q0,q1,q2,q3,q4,q5,q6 {
  h q0;
  operate_iteration_0 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_1 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_2 q0,q1,q2,q3,q4,q6;
  operate_iteration_3 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_4 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_5 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_6 q0,q1,q2,q3,q4,q6;
  operate_iteration_7 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_8 q0,q1,q2,q3,q4,q5;
  operate_iteration_9 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_10 q0,q1,q2,q3,q4,q6;
  operate_iteration_11 q0,q1,q2,q3,q4,q6;
  operate_iteration_12 q0,q1,q2,q3,q4,q6;
  operate_iteration_13 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_14 q0,q1,q2,q3,q4,q6;
  operate_iteration_15 q0,q1,q2,q3,q4,q5,q6;
}

gate mcx_hybrid_gray_code_maslov15_139643817710736 q0,q1,q2,q3,q4 {
  r1tof q0,q1,q4;
  ccx q4,q2,q3;
  r1tof q0,q1,q4;
}

gate mcx_hybrid_gray_code_maslov15_o0_139643817714000_o0 q0,q1,q2,q3,q4 {
  x q0;
  x q1;
  x q2;
  mcx_hybrid_gray_code_maslov15_139643817710736 q0,q1,q2,q3,q4;
  x q0;
  x q1;
  x q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_o0_139643817714000_o0 q0,q1,q2,q3,q4;
}

gate mcx_hybrid_gray_code_maslov15_139643817710992 q0,q1,q2,q3,q4 {
  r1tof q0,q1,q4;
  ccx q4,q2,q3;
  r1tof q0,q1,q4;
}

gate mcx_hybrid_gray_code_maslov15_o0_139643779224528_o0 q0,q1,q2,q3,q4 {
  x q0;
  x q1;
  x q2;
  mcx_hybrid_gray_code_maslov15_139643817710992 q0,q1,q2,q3,q4;
  x q0;
  x q1;
  x q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_o0_139643779224528_o0 q0,q1,q2,q3,q4;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse q0,q1,q2,q3,q4 {
  ry(-0.30627736916966936) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_0_qinverse q1,q2,q3,q0,q4;
  ry(0.30627736916966936) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_1_qinverse q1,q2,q3,q0,q4;
}

gate mcx_hybrid_gray_code_maslov15_139644181561744 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_139643817710544_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_139644181561744 q0,q1,q2;
  x q0;
  x q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_139643817710544_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_139644181564752 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_139644181576464_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_139644181564752 q0,q1,q2;
  x q0;
  x q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_139644181576464_o0 q0,q1,q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse q0,q1,q2 {
  ry(-0.06842744166965213) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(0.06842744166965213) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse q0,q1 {
  ry(-0.001961335930211545) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(0.001961335930211545) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate prep_ancilla_1_statepreparation_qinverse q0,q1,q2,q3,q4 {
  prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse q0,q1,q2,q3,q4;
  prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse q1,q2,q3;
  prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse q2,q3;
  ry(-9.527425386396606e-07) q3;
}

gate main_prep_ancilla_1 q0,q1,q2,q3,q4 {
  prep_ancilla_1_statepreparation_qinverse q0,q1,q2,q3,q4;
}

qreg q[7];
main_identity_0 q[0];
main_identity_1 q[1],q[2],q[3],q[4];
main_prep_ancilla_0 q[1],q[2],q[3],q[4],q[5];
main_operate q[0],q[1],q[2],q[3],q[4],q[5],q[6];
id q[0];
main_prep_ancilla_1 q[1],q[2],q[3],q[4],q[5];
