// Generated by Classiq.
// Classiq version: 0.50.0
// Creation timestamp: 2024-09-26T02:59:36.493993+00:00
// Random seed: 2307696162

OPENQASM 2.0;
include "qelib1.inc";
gate main_identity_0 q0 {
}

gate main_identity_1 q0,q1,q2,q3 {
}

gate prep_ancilla_0_statepreparation_computationalbasisstatepreparation q0,q1,q2,q3 {
}

gate prep_ancilla_0_statepreparation q0,q1,q2,q3 {
  prep_ancilla_0_statepreparation_computationalbasisstatepreparation q0,q1,q2,q3;
}

gate main_prep_ancilla_0 q0,q1,q2,q3 {
  prep_ancilla_0_statepreparation q0,q1,q2,q3;
}

gate operate_iteration_0_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
  x q3;
}

gate r1tof4 q0,q1,q2,q3 {
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
}

gate r1tof4_dg q0,q1,q2,q3 {
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  t q3;
  cx q0,q3;
  tdg q3;
  cx q1,q3;
  h q3;
  t q3;
  cx q2,q3;
  tdg q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4,q5 {
  r1tof4 q0,q1,q2,q5;
  ccx q5,q3,q4;
  r1tof4_dg q0,q1,q2,q5;
}

gate operate_iteration_0_igate_mcx_0 q0,q1,q2,q3,q4,q5 {
  mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4,q5;
}

gate ccircuit_19044 q0,q1 {
}

gate operate_iteration_0_igate q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  ccircuit_19044 q5,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
}

gate operate_iteration_0_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
  x q1;
  x q0;
}

gate operate_iteration_0 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_0_igate q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_0_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_1_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
  x q2;
  x q3;
}

gate rcccx q0,q1,q2,q3 {
  u2(0,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(0,pi) q3;
}

gate rcccx_dg q0,q1,q2,q3 {
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u1(pi/4) q3;
  cx q1,q3;
  u1(-pi/4) q3;
  cx q0,q3;
  u2(-2*pi,pi) q3;
  u1(pi/4) q3;
  cx q2,q3;
  u1(-pi/4) q3;
  u2(-2*pi,pi) q3;
}

gate mcx q0,q1,q2,q3,q4 {
  h q4;
  cu1(pi/2) q3,q4;
  h q4;
  rcccx q0,q1,q2,q3;
  h q4;
  cu1(-pi/2) q3,q4;
  h q4;
  rcccx_dg q0,q1,q2,q3;
  c3sqrtx q0,q1,q2,q4;
}

gate mcx_hybrid_gray_code_maslov15_140494028619088 q0,q1,q2,q3,q4 {
  mcx q0,q1,q2,q3,q4;
}

gate operate_iteration_1_compose_mcx_0 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140494028619088 q0,q1,q2,q3,q4;
}

gate ccompose_expanded___12 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_1_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___12 q0,q1;
}

gate operate_iteration_1_compose q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  operate_iteration_1_compose_compose_aux_control_name q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_1_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
  x q1;
}

gate operate_iteration_1 q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_1_compose q0,q1,q2,q3,q4,q5;
  operate_iteration_1_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_2_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q2;
  x q3;
}

gate operate_iteration_2_rzgate q0,q1,q2,q3,q4,q5 {
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(2*pi) q0;
}

gate operate_iteration_2_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
  x q0;
}

gate operate_iteration_2 q0,q1,q2,q3,q4,q5 {
  operate_iteration_2_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_2_rzgate q0,q1,q2,q3,q4,q5;
  operate_iteration_2_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_3_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q2;
  x q3;
}

gate ccompose_expanded___25 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_3_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___25 q0,q1;
}

gate operate_iteration_3_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
  operate_iteration_3_compose_compose_aux_control_name q6,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
}

gate operate_iteration_3_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q2;
}

gate operate_iteration_3 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_3_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_3_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_3_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_4_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q3;
}

gate operate_iteration_4_igate q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  ccircuit_19044 q5,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
}

gate operate_iteration_4_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q1;
  x q0;
}

gate operate_iteration_4 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_4_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_4_igate q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_4_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_5_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
  x q3;
}

gate ccompose_expanded___38 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_5_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___38 q0,q1;
}

gate operate_iteration_5_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
  operate_iteration_5_compose_compose_aux_control_name q6,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
}

gate operate_iteration_5_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q1;
}

gate operate_iteration_5 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_5_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_5_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_5_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_6_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q3;
}

gate operate_iteration_6_rzgate q0,q1,q2,q3,q4 {
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(2*pi) q0;
}

gate operate_iteration_6_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
  x q0;
}

gate operate_iteration_6 q0,q1,q2,q3,q4 {
  operate_iteration_6_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_6_rzgate q0,q1,q2,q3,q4;
  operate_iteration_6_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_7_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q3;
}

gate ccompose_expanded___51 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_7_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___51 q0,q1;
}

gate operate_iteration_7_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
  operate_iteration_7_compose_compose_aux_control_name q6,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
}

gate operate_iteration_7_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q3;
}

gate operate_iteration_7 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_7_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_7_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_7_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_8_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
  x q2;
}

gate operate_iteration_8_igate q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  ccircuit_19044 q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_8_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
  x q1;
  x q0;
}

gate operate_iteration_8 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_8_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_8_igate q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_8_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_9_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
  x q2;
}

gate ccompose_expanded___64 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_9_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___64 q0,q1;
}

gate operate_iteration_9_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  operate_iteration_9_compose_compose_aux_control_name q5,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
}

gate operate_iteration_9_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
  x q1;
}

gate operate_iteration_9 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_9_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_9_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_9_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_10_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q2;
}

gate operate_iteration_10_rzgate q0,q1,q2,q3,q4 {
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(2*pi) q0;
}

gate operate_iteration_10_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
  x q0;
}

gate operate_iteration_10 q0,q1,q2,q3,q4 {
  operate_iteration_10_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_10_rzgate q0,q1,q2,q3,q4;
  operate_iteration_10_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_11_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q2;
}

gate ccompose_expanded___77 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_11_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___77 q0,q1;
}

gate operate_iteration_11_compose q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  operate_iteration_11_compose_compose_aux_control_name q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_11_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q2;
}

gate operate_iteration_11 q0,q1,q2,q3,q4,q5 {
  operate_iteration_11_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_11_compose q0,q1,q2,q3,q4,q5;
  operate_iteration_11_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_12_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
  x q1;
}

gate operate_iteration_12_igate q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q6,q5;
  ccircuit_19044 q6,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q6;
}

gate operate_iteration_12_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q1;
  x q0;
}

gate operate_iteration_12 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_12_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_12_igate q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_12_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_13_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q1;
}

gate ccompose_expanded___90 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_13_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___90 q0,q1;
}

gate operate_iteration_13_compose q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q5,q6;
  operate_iteration_13_compose_compose_aux_control_name q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_13_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q1;
}

gate operate_iteration_13 q0,q1,q2,q3,q4,q5,q6 {
  operate_iteration_13_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_13_compose q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_13_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate operate_iteration_14_inplace_prepare_int_0 q0,q1,q2,q3 {
  x q0;
}

gate operate_iteration_14_rzgate q0,q1,q2,q3,q4,q5 {
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4,q0,q5;
  rz(-pi) q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q0;
  rz(2*pi) q0;
}

gate operate_iteration_14_inplace_prepare_int_1 q0,q1,q2,q3 {
  x q0;
}

gate operate_iteration_14 q0,q1,q2,q3,q4,q5 {
  operate_iteration_14_inplace_prepare_int_0 q1,q2,q3,q4;
  operate_iteration_14_rzgate q0,q1,q2,q3,q4,q5;
  operate_iteration_14_inplace_prepare_int_1 q1,q2,q3,q4;
}

gate ccompose_expanded___98 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_15_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___98 q0,q1;
}

gate operate_iteration_15_compose q0,q1,q2,q3,q4,q5 {
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
  operate_iteration_15_compose_compose_aux_control_name q5,q0;
  operate_iteration_1_compose_mcx_0 q1,q2,q3,q4,q5;
}

gate operate_iteration_15 q0,q1,q2,q3,q4,q5 {
  operate_iteration_15_compose q0,q1,q2,q3,q4,q5;
}

gate main_operate q0,q1,q2,q3,q4,q5,q6 {
  h q0;
  operate_iteration_0 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_1 q0,q1,q2,q3,q4,q5;
  operate_iteration_2 q0,q1,q2,q3,q4,q5;
  operate_iteration_3 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_4 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_5 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_6 q0,q1,q2,q3,q4;
  operate_iteration_7 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_8 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_9 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_10 q0,q1,q2,q3,q4;
  operate_iteration_11 q0,q1,q2,q3,q4,q5;
  operate_iteration_12 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_13 q0,q1,q2,q3,q4,q5,q6;
  operate_iteration_14 q0,q1,q2,q3,q4,q5;
  operate_iteration_15 q0,q1,q2,q3,q4,q5;
}

gate prep_ancilla_1_statepreparation_qinverse_computationalbasisstatepreparation_qinverse q0,q1,q2,q3 {
}

gate prep_ancilla_1_statepreparation_qinverse q0,q1,q2,q3 {
  prep_ancilla_1_statepreparation_qinverse_computationalbasisstatepreparation_qinverse q0,q1,q2,q3;
}

gate main_prep_ancilla_1 q0,q1,q2,q3 {
  prep_ancilla_1_statepreparation_qinverse q0,q1,q2,q3;
}

qreg q[7];
main_identity_0 q[0];
main_identity_1 q[1],q[2],q[3],q[4];
main_prep_ancilla_0 q[1],q[2],q[3],q[4];
main_operate q[0],q[1],q[2],q[3],q[4],q[5],q[6];
id q[0];
main_prep_ancilla_1 q[1],q[2],q[3],q[4];
