// Generated by Classiq.
// Classiq version: 0.50.0
// Creation timestamp: 2024-09-26T03:03:00.274112+00:00
// Random seed: 311974026

OPENQASM 2.0;
include "qelib1.inc";
gate main_identity_0 q0 {
}

gate main_identity_1 q0,q1,q2 {
}

gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate prep_ancilla_0_statepreparation_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate prep_ancilla_0_statepreparation_rygate_1 q0,q1 {
  prep_ancilla_0_statepreparation_rygate_1_mcx_0 q1,q0;
  ry(-pi/6) q0;
  prep_ancilla_0_statepreparation_rygate_1_mcx_0 q1,q0;
  ry(pi/6) q0;
}

gate mcx_hybrid_gray_code_maslov15_140493815947600 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_140494029864848_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140493815947600 q0,q1,q2;
  x q0;
  x q1;
}

gate prep_ancilla_0_statepreparation_rygate_2_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_140494029864848_o0 q0,q1,q2;
}

gate prep_ancilla_0_statepreparation_rygate_2 q0,q1,q2 {
  prep_ancilla_0_statepreparation_rygate_2_mcx_0 q1,q2,q0;
  ry(-pi/4) q0;
  prep_ancilla_0_statepreparation_rygate_2_mcx_0 q1,q2,q0;
  ry(pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140494051723152 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140494051723152 q0,q1,q2;
  x q1;
}

gate prep_ancilla_0_statepreparation_rygate_3_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2;
}

gate prep_ancilla_0_statepreparation_rygate_3 q0,q1,q2 {
  prep_ancilla_0_statepreparation_rygate_3_mcx_0 q1,q2,q0;
  ry(-pi/6) q0;
  prep_ancilla_0_statepreparation_rygate_3_mcx_0 q1,q2,q0;
  ry(pi/6) q0;
}

gate prep_ancilla_0_statepreparation_rygate_4_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15 q0,q1;
}

gate prep_ancilla_0_statepreparation_rygate_4 q0,q1 {
  prep_ancilla_0_statepreparation_rygate_4_mcx_0 q1,q0;
  ry(-0.1763238388157515) q0;
  prep_ancilla_0_statepreparation_rygate_4_mcx_0 q1,q0;
  ry(0.1763238388157515) q0;
}

gate mcx_hybrid_gray_code_maslov15_140494059207120 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140494059207120 q0,q1,q2;
  x q0;
}

gate prep_ancilla_0_statepreparation_rygate_5_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o2 q0,q1,q2;
}

gate prep_ancilla_0_statepreparation_rygate_5 q0,q1,q2 {
  prep_ancilla_0_statepreparation_rygate_5_mcx_0 q1,q2,q0;
  ry(-0.4205343352839653) q0;
  prep_ancilla_0_statepreparation_rygate_5_mcx_0 q1,q2,q0;
  ry(0.4205343352839653) q0;
}

gate prep_ancilla_0_statepreparation q0,q1,q2 {
  ry(0.27640107456771995) q2;
  prep_ancilla_0_statepreparation_rygate_1 q1,q2;
  prep_ancilla_0_statepreparation_rygate_2 q0,q1,q2;
  prep_ancilla_0_statepreparation_rygate_3 q0,q1,q2;
  prep_ancilla_0_statepreparation_rygate_4 q1,q2;
  prep_ancilla_0_statepreparation_rygate_5 q0,q1,q2;
}

gate main_prep_ancilla_0 q0,q1,q2 {
  prep_ancilla_0_statepreparation q0,q1,q2;
}

gate operate_iteration_0_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
  x q2;
}

gate mcx q0,q1,q2,q3 {
  h q3;
  p(pi/8) q0;
  p(pi/8) q1;
  p(pi/8) q2;
  p(pi/8) q3;
  cx q0,q1;
  p(-pi/8) q1;
  cx q0,q1;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  p(pi/8) q2;
  cx q1,q2;
  p(-pi/8) q2;
  cx q0,q2;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q1,q3;
  p(pi/8) q3;
  cx q2,q3;
  p(-pi/8) q3;
  cx q0,q3;
  h q3;
}

gate mcx_hybrid_gray_code_maslov15_140494058632272 q0,q1,q2,q3 {
  mcx q0,q1,q2,q3;
}

gate operate_iteration_0_igate_mcx_0 q0,q1,q2,q3 {
  mcx_hybrid_gray_code_maslov15_140494058632272 q0,q1,q2,q3;
}

gate ccircuit_26122 q0,q1 {
}

gate operate_iteration_0_igate q0,q1,q2,q3,q4 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4;
  ccircuit_26122 q4,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4;
}

gate operate_iteration_0_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
  x q0;
}

gate operate_iteration_0 q0,q1,q2,q3,q4 {
  operate_iteration_0_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_0_igate q0,q1,q2,q3,q4;
  operate_iteration_0_inplace_prepare_int_1 q1,q2,q3;
}

gate operate_iteration_1_inplace_prepare_int_0 q0,q1,q2 {
  x q1;
  x q2;
}

gate ccompose_expanded___10 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_1_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___10 q0,q1;
}

gate operate_iteration_1_compose q0,q1,q2,q3,q4 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4;
  operate_iteration_1_compose_compose_aux_control_name q4,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4;
}

gate operate_iteration_1_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
}

gate operate_iteration_1 q0,q1,q2,q3,q4 {
  operate_iteration_1_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_1_compose q0,q1,q2,q3,q4;
  operate_iteration_1_inplace_prepare_int_1 q1,q2,q3;
}

gate operate_iteration_2_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q2;
}

gate r1tof q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140494020567056 q0,q1,q2,q3,q4 {
  r1tof q0,q1,q4;
  ccx q4,q2,q3;
  r1tof q0,q1,q4;
}

gate operate_iteration_2_rzgate_mcx_1 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140494020567056 q0,q1,q2,q3,q4;
}

gate operate_iteration_2_rzgate q0,q1,q2,q3,q4 {
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q0;
  rz(-pi) q0;
  operate_iteration_2_rzgate_mcx_1 q1,q2,q3,q0,q4;
  rz(2*pi) q0;
}

gate operate_iteration_2_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q0;
}

gate operate_iteration_2 q0,q1,q2,q3,q4 {
  operate_iteration_2_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_2_rzgate q0,q1,q2,q3,q4;
  operate_iteration_2_inplace_prepare_int_1 q1,q2,q3;
}

gate operate_iteration_3_inplace_prepare_int_0 q0,q1,q2 {
  x q2;
}

gate ccompose_expanded___21 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_3_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___21 q0,q1;
}

gate operate_iteration_3_compose q0,q1,q2,q3,q4,q5 {
  operate_iteration_2_rzgate_mcx_1 q1,q2,q3,q5,q4;
  operate_iteration_3_compose_compose_aux_control_name q5,q0;
  operate_iteration_2_rzgate_mcx_1 q1,q2,q3,q5,q4;
}

gate operate_iteration_3_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
}

gate operate_iteration_3 q0,q1,q2,q3,q4,q5 {
  operate_iteration_3_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_3_compose q0,q1,q2,q3,q4,q5;
  operate_iteration_3_inplace_prepare_int_1 q1,q2,q3;
}

gate operate_iteration_4_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
}

gate operate_iteration_4_igate q0,q1,q2,q3,q4,q5 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q5;
  ccircuit_26122 q5,q0;
  operate_iteration_2_rzgate_mcx_1 q1,q2,q3,q5,q4;
}

gate operate_iteration_4_inplace_prepare_int_1 q0,q1,q2 {
  x q1;
  x q0;
}

gate operate_iteration_4 q0,q1,q2,q3,q4,q5 {
  operate_iteration_4_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_4_igate q0,q1,q2,q3,q4,q5;
  operate_iteration_4_inplace_prepare_int_1 q1,q2,q3;
}

gate operate_iteration_5_inplace_prepare_int_0 q0,q1,q2 {
  x q1;
}

gate ccompose_expanded___32 q0,q1 {
  cx q0,q1;
  cz q0,q1;
}

gate operate_iteration_5_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___32 q0,q1;
}

gate operate_iteration_5_compose q0,q1,q2,q3,q4,q5 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q5;
  operate_iteration_5_compose_compose_aux_control_name q5,q0;
  operate_iteration_2_rzgate_mcx_1 q1,q2,q3,q5,q4;
}

gate operate_iteration_5_inplace_prepare_int_1 q0,q1,q2 {
  x q1;
}

gate operate_iteration_5 q0,q1,q2,q3,q4,q5 {
  operate_iteration_5_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_5_compose q0,q1,q2,q3,q4,q5;
  operate_iteration_5_inplace_prepare_int_1 q1,q2,q3;
}

gate operate_iteration_6_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
}

gate operate_iteration_6_rzgate q0,q1,q2,q3,q4 {
  rz(-pi) q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q0;
  rz(-pi) q0;
  operate_iteration_2_rzgate_mcx_1 q1,q2,q3,q0,q4;
  rz(2*pi) q0;
}

gate operate_iteration_6_inplace_prepare_int_1 q0,q1,q2 {
  x q0;
}

gate operate_iteration_6 q0,q1,q2,q3,q4 {
  operate_iteration_6_inplace_prepare_int_0 q1,q2,q3;
  operate_iteration_6_rzgate q0,q1,q2,q3,q4;
  operate_iteration_6_inplace_prepare_int_1 q1,q2,q3;
}

gate ccompose_expanded___39 q0,q1 {
  cz q0,q1;
  cx q0,q1;
}

gate operate_iteration_7_compose_compose_aux_control_name q0,q1 {
  ccompose_expanded___39 q0,q1;
}

gate operate_iteration_7_compose q0,q1,q2,q3,q4 {
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4;
  operate_iteration_7_compose_compose_aux_control_name q4,q0;
  operate_iteration_0_igate_mcx_0 q1,q2,q3,q4;
}

gate operate_iteration_7 q0,q1,q2,q3,q4 {
  operate_iteration_7_compose q0,q1,q2,q3,q4;
}

gate main_operate q0,q1,q2,q3,q4,q5 {
  h q0;
  operate_iteration_0 q0,q1,q2,q3,q4;
  operate_iteration_1 q0,q1,q2,q3,q4;
  operate_iteration_2 q0,q1,q2,q3,q4;
  operate_iteration_3 q0,q1,q2,q3,q4,q5;
  operate_iteration_4 q0,q1,q2,q3,q4,q5;
  operate_iteration_5 q0,q1,q2,q3,q4,q5;
  operate_iteration_6 q0,q1,q2,q3,q5;
  operate_iteration_7 q0,q1,q2,q3,q5;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o2 q0,q1,q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o2 q0,q1,q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse q0,q1,q2 {
  ry(-0.4205343352839653) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(0.4205343352839653) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15 q0,q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15 q0,q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse q0,q1 {
  ry(-0.1763238388157515) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_0_qinverse q1,q0;
  ry(0.1763238388157515) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse_mcx_1_qinverse q1,q0;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o1 q0,q1,q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse q0,q1,q2 {
  ry(-pi/6) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/6) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140493815533456 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_140493815531920_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140493815533456 q0,q1,q2;
  x q0;
  x q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_3_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_140493815531920_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140493815531088 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_o0_140493815538512_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140493815531088 q0,q1,q2;
  x q0;
  x q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_3_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_o0_140493815538512_o0 q0,q1,q2;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_3_qinverse q0,q1,q2 {
  ry(-pi/4) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_3_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/4) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_3_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_4_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_4_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate prep_ancilla_1_statepreparation_qinverse_rygate_4_qinverse q0,q1 {
  ry(-pi/6) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_4_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/6) q0;
  prep_ancilla_1_statepreparation_qinverse_rygate_4_qinverse_mcx_1_qinverse q1,q0;
}

gate prep_ancilla_1_statepreparation_qinverse q0,q1,q2 {
  prep_ancilla_1_statepreparation_qinverse_rygate_0_qinverse q0,q1,q2;
  prep_ancilla_1_statepreparation_qinverse_rygate_1_qinverse q1,q2;
  prep_ancilla_1_statepreparation_qinverse_rygate_2_qinverse q0,q1,q2;
  prep_ancilla_1_statepreparation_qinverse_rygate_3_qinverse q0,q1,q2;
  prep_ancilla_1_statepreparation_qinverse_rygate_4_qinverse q1,q2;
  ry(-0.27640107456771995) q2;
}

gate main_prep_ancilla_1 q0,q1,q2 {
  prep_ancilla_1_statepreparation_qinverse q0,q1,q2;
}

qreg q[6];
main_identity_0 q[0];
main_identity_1 q[1],q[2],q[3];
main_prep_ancilla_0 q[1],q[2],q[3];
main_operate q[0],q[1],q[2],q[3],q[4],q[5];
id q[0];
main_prep_ancilla_1 q[1],q[2],q[3];
